services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: public
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

  api:
    build:
      context: ./flux-api
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./flux-api:/app

  web:
    build:
      context: ./flux-web
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    ports:
      - "4200:4200"
    depends_on:
      - api
    volumes:
      - ./flux-web:/app